# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'MarvelHero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.0'
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.6.0'
  pod 'RealmSwift'
  pod 'FirebaseMessaging'
  # Pods for MarvelHero

end
